[template.environment]
  GQL_HOST = "https://woo.emisija.lt/graphql"
  NUXT_IMAGE_DOMAINS = "https://woo.emisija.lt"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://secure.woonuxt.com/.*"]
