query GetCart {
  cart {
    contents {
      itemCount
      nodes {
        product {
          node {
            databaseId
            name
            ... on SimpleProduct {
              price
            }
          }
        }
        quantity
        total
      }
    }
    subtotal
    total
  }
}
