mutation loginWithProvider($username: String!, $password: String!) {
  login(input: { username: $username, password: $password }) {
    authToken
    refreshToken
    user {
      id
      username
      email
    }
  }
}
